### ISSUE TITLE
Upgrade to NAN v2.0.9

### ISSUE THREAD

**Issue by piranna** [NodeOS/nodeos-mount#3]
NAN version was set with an asterisk and automatically fetch NAN v2.0.9 from 31st July, that change and remove some APIs and don't work with Node.js v0.11.14. I've upgraded it to use version v1.9.0 (latest from branch 1.x.x), but this will need to be changed to new NAN. @netlovers, could you be able to review it?

**Comment by netlovers** [comment]
I'll check when I have a bit more time. But I guess, we need to support the latest version, if you want to use the newest node.js versions.

**Comment by piranna** [comment]
Ok, thank you :-) It's not in a hurry, I'll try to make it work with v0.11.14 since there's some problems with the upgrade to Node.js 4.1.0, so take your time :-)

**Comment by piranna** [comment]
[fuse-bindings is upgrading to nan2 too](https://github.com/mafintosh/fuse-bindings/tree/nan2), so it could be useful to see how they are doing it. Seems the biggest change is the change to use a C++ namespace.

**Comment by piranna** [comment]
This is already done is master, clossing.
